# Numpy

In [2]:
import numpy as np  #import numpy
import sys

In [3]:
a = np.array([1,2,3] , dtype='int8') # 1D materix

In [4]:
a

array([1, 2, 3], dtype=int8)

In [5]:
b = np.array([[1,2,3],[4,5,6]]) # 2D materix

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[7,8,9]]]) # 3D materix

In [8]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [7, 8, 9]]])

In [9]:
b.ndim      # Get Dimension

2

In [10]:
c.ndim 

3

In [11]:
b.shape      # Get shape

(2, 3)

In [12]:
c.shape

(2, 2, 3)

In [13]:
b.dtype       # Get Type

dtype('int32')

In [14]:
a.dtype

dtype('int8')

In [15]:
b.itemsize    # Get Element size

4

In [16]:
c.itemsize

4

In [17]:
b.size      # Get Matrix in elements

6

In [18]:
c.size

12

In [19]:
b.itemsize * b.size     # Get total size

24

In [20]:
b.nbytes     # Get total size

24

In [21]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
a[1,-2]     # Get specific element ( 1 is row and -2 is column )

9

In [24]:
a[0,3]    

4

In [25]:
a[0,:]     # Get specific row 

array([1, 2, 3, 4, 5])

In [26]:
a[1,:]    

array([ 6,  7,  8,  9, 10])

In [27]:
a[:,0]     # Get specific column

array([1, 6])

In [28]:
a[:,3]

array([4, 9])

In [29]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
a[0,1:-1:1]  # Getting elements using range  (starting index : ending index : stepsize)

array([2, 3, 4])

In [31]:
a[1,0:-1:2]

array([6, 8])

In [32]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
a[1,4]=100    # Change value

In [34]:
a

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 100]])

In [35]:
a[:,2] = 50       # Column values changes

In [36]:
a

array([[  1,   2,  50,   4,   5],
       [  6,   7,  50,   9, 100]])

In [37]:
a[1,:] = 88       # Row values changes

In [38]:
a

array([[ 1,  2, 50,  4,  5],
       [88, 88, 88, 88, 88]])

In [39]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [7, 8, 9]]])

In [40]:
# Get specific element
c[0,1,2]

6

In [41]:
# Row values replace in 3D materix
c[:,1,:] = [[10,11,12],[20,30,40]] 

In [42]:
c

array([[[ 1,  2,  3],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [20, 30, 40]]])

In [43]:
# All 0s matrix
np.zeros(5)  # 1D materix

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,3))    # 2D materix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((2,3,3))    # 3D materix

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
#  All 1s matrix
np.ones((5))

array([1., 1., 1., 1., 1.])

In [47]:
np.ones((3,5))    # 2D materix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.ones((2,4,4), dtype='int32')    # 3D materix

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [49]:
# Any number using create an materix
np.full((2,3),55)

array([[55, 55, 55],
       [55, 55, 55]])

In [50]:
np.full((4,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [51]:
# Full like using create an materix
np.full_like(a,55)  # 'a' array using create materix

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [52]:
np.full_like(b,88)  # 'b' array using create materix

array([[88, 88, 88],
       [88, 88, 88]])

In [53]:
# Random number using create an materix
np.random.rand(3,3)

array([[0.10871055, 0.05047142, 0.17786145],
       [0.22974333, 0.37512187, 0.50067502],
       [0.09229719, 0.78073371, 0.85060475]])

In [54]:
 # Random interger values using create a materix
np.random.randint(10, size=(3,3))

array([[0, 6, 2],
       [1, 1, 0],
       [9, 3, 5]])

In [55]:
np.random.randint(50, size=(5,5))

array([[ 4, 20,  8, 26, 47],
       [27,  6, 21, 35, 31],
       [48, 20, 30, 33, 32],
       [ 5, 36, 31, 22,  0],
       [12,  0, 12, 45, 43]])

In [56]:
# Random values and shape using create a materix 
np.random.randint(1,10, a.shape) 

array([[6, 6, 2, 7, 1],
       [8, 1, 9, 6, 8]])

In [57]:
np.random.randint(-10,30, c.shape) 

array([[[ 6,  1, -3],
        [-9, -5, 13]],

       [[ 2, 13, 12],
        [23, -3, 14]]])

In [58]:
# The identity matrix
np.identity(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
 # Repeat array using crete a matrix
ar = np.array([[1,2,3]])
d = np.repeat(ar,3,axis=0)

In [108]:
d

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [63]:
array = np.array([[1,2,3,4]])
e = np.repeat(array,5,axis=0)

In [64]:
e

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [65]:
ar = np.array([1,2,3])
f = np.repeat(ar,4,axis=0)

In [66]:
f

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [67]:
a = np.array([[1,2,3],[4,5,6]])

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
# Matrix copy in another veriable that time use a copy()
b = a.copy()

In [70]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [72]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [73]:
a ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [74]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [75]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
c = a+b

In [78]:
c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [79]:
c % 3

array([[2, 1, 0],
       [2, 1, 0]], dtype=int32)

In [80]:
# Take the trignomatric 
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [81]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [82]:
a = np.array([[1,1],[2,2],[3,3]])
b = np.array([[2,2,2],[2,2,2]])

In [83]:
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [84]:
b

array([[2, 2, 2],
       [2, 2, 2]])

In [85]:
# matrix a and b multiplication
np.matmul(a,b)

array([[ 4,  4,  4],
       [ 8,  8,  8],
       [12, 12, 12]])

In [86]:
a = np.array([[1,2,3],[4,15,6],[7,8,9]])

In [87]:
a

array([[ 1,  2,  3],
       [ 4, 15,  6],
       [ 7,  8,  9]])

In [88]:
# Get max element in Column
a.max(axis=0)  

array([ 7, 15,  9])

In [89]:
# Get max element in Row
a.max(axis=1)  

array([ 3, 15,  9])

In [90]:
a.sum(axis=0) 

array([12, 25, 18])

In [91]:
a.sum(axis=1)

array([ 6, 25, 24])

In [92]:
a.mean(axis=0)

array([4.        , 8.33333333, 6.        ])

In [93]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [94]:
# Find the determinant
c = np.random.randint(50, size=(5,5))
np.linalg.det(c)

7010395.000000009

In [95]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [96]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
# Reshape 
b = a.reshape((4,2))

In [98]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [99]:
# virtically stacking vectors
r1 = [1,2,3,4,5]
r2 = [6,7,8,9,10]

np.vstack([r1,r2,r2,r1])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [100]:
# horizontal stack
c1 = [1,4,7]
c2 = [2,5,8]
c = np.vstack([c1,c2])
d = np.array([[2,2],[3,3]])
np.hstack([c,d])

array([[1, 4, 7, 2, 2],
       [2, 5, 8, 3, 3]])

In [101]:
# Loading data file
data = np.genfromtxt('Demodata.txt' , delimiter=',')
data = data.astype('int32')

In [102]:
data

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65]])

In [103]:
test = np.genfromtxt('Test.txt' , delimiter = ' ')
test = test.astype('int32')


In [104]:
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
# boolean Function
test>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [106]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[2,5,8]]

array([3, 6, 9])

In [109]:
a = np.array([[1,2,3],[4,15,6],[7,8,9]])

In [110]:
a

array([[ 1,  2,  3],
       [ 4, 15,  6],
       [ 7,  8,  9]])

In [112]:
# Transpose of matrix
a.T

array([[ 1,  4,  7],
       [ 2, 15,  8],
       [ 3,  6,  9]])

In [113]:
a.transpose()

array([[ 1,  4,  7],
       [ 2, 15,  8],
       [ 3,  6,  9]])

In [114]:
# Conjugate transpose of a matrix
a.conj().T

array([[ 1,  4,  7],
       [ 2, 15,  8],
       [ 3,  6,  9]])

In [115]:
a.conj().transpose()

array([[ 1,  4,  7],
       [ 2, 15,  8],
       [ 3,  6,  9]])